#!/bin/sh
set -eu
export TESTING=1
PY_FILES=$(find . -type f -name "*.py")

export SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI:-}

rm -rf ./shippable
mkdir -p ./shippable/testresults ./shippable/codecoverage

cleanup() {
    [ -f ./coverage.xml ] && mv ./coverage.xml ./shippable/codecoverage
}

trap cleanup EXIT

python3 -m pep8 $PY_FILES
python3 -m pylint -E backend
python3 -m pytest \
       --junitxml ./shippable/testresults/pytest.xml \
       --doctest-modules \
       --cov=backend \
       --cov-report term \
       --cov-report xml \
       --cov-report html \
       --pyargs backend
