#!/bin/sh
set -eu
export DEBUG=0
export TESTING=0
cd /app
exec chpst -u app   \
     uwsgi_python27 \
     --master       \
     --http-socket :$PORT              \
     --processes ${UWSGI_PROCESSES:-2} \
     --threads ${UWSGI_THREADS:-32}    \
     --module backend \
     --callable app
