#!/bin/sh
set -eux

### --> ATTENTION DEVELOPERS <-- ###
# This is where you set up your local provisioning.
# DO:
# - Keep It Simple, Silly
# - Talk to your sysop
# DO NOT:
# - Make this a horrible mess
# - Install 5GB of random crap
# - Make this the only possible way to get your application running
# CONSIDER:
# - This is only to get the app running in your local environment
# - What is necessary to run this in production? You don't run Vagrant on AWS
# - Deployment setup is not your responsibility

id

export DEBIAN_FRONTEND=noninteractive
dpkg --configure -a
apt-get update
apt-get install --yes --no-install-recommends \
        git-core \
        libffi-dev \
        libpq-dev \
        postgresql-9.4 \
        python-dev \
        python-pip \
        python-wheel \
        && true

git show -s HEAD
git status

pip install -r ./requirements-dev.txt
pip install -r ./requirements.txt

# Bring up postgres, create databases for local dev and testing
cat > /etc/postgresql/9.4/main/pg_hba.conf <<EOF
local   all             postgres                                trust
host    all             postgres        127.0.0.1/32            trust
host    all             postgres        ::1/128                 trust
EOF
service postgresql restart
psql -U postgres -Atc 'select 1;'
./cmd/db_create local
./cmd/db_create test
# Create tables for the local dev environment
export PYTHONPATH=.
export SQLALCHEMY_DATABASE_URI="postgresql://postgres@localhost/local"
./cmd/db_create_tables
